// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class PredownloadConfig {
  PredownloadConfig({
    required this.urls,
    required this.shouldPreloadFirstSegment,
  });

  List<String?> urls;

  bool shouldPreloadFirstSegment;

  Object encode() {
    return <Object?>[
      urls,
      shouldPreloadFirstSegment,
    ];
  }

  static PredownloadConfig decode(Object result) {
    result as List<Object?>;
    return PredownloadConfig(
      urls: (result[0] as List<Object?>?)!.cast<String?>(),
      shouldPreloadFirstSegment: result[1]! as bool,
    );
  }
}

class _PredownloadPigeonCodec extends StandardMessageCodec {
  const _PredownloadPigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PredownloadConfig) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PredownloadConfig.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PredownloadPigeon {
  /// Constructor for [PredownloadPigeon].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PredownloadPigeon({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _PredownloadPigeonCodec();

  Future<void> predownloadDownload(PredownloadConfig arg_config) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.bccm_player.PredownloadPigeon.predownloadDownload', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_config]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}
