site_name: BccmPlayer docs
docs_dir: doc/
theme:
  name: readthedocs
plugins:
  - exclude:
      glob:
        - api/*
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
